# server port config
server : 
  port : 8001
  
spring:
  datasource:
    url: jdbc:oracle:thin:@oracle_high?TNS_ADMIN=/Users/hyeweonyoo/Downloads/Wallet_oracle
    driver-class-name: oracle.jdbc.OracleDriver
    username: workhub
    password: adminADMIN11
    
# mybatis config
mybatis : 
  mapper-locations : mappers/**/*.xml
  