# server port config
server : 
  port : 8001
  
spring: 
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: C##WORKHUB
    password: WORKHUB
    
# mybatis config
mybatis : 
  mapper-locations : mappers/**/*.xml
  
  